# Generated by Django 6.0.3 on 2026-03-14 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_consumers_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumers',
            new_name='Documents',
        ),
    ]
