# Generated by Django 6.0.3 on 2026-03-17 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_documents_status_documents_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('sentiment', models.CharField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='main.documents')),
            ],
        ),
    ]
