# Generated by Django 6.0.3 on 2026-03-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_documents_pdf_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
