# Generated by Django 6.0.3 on 2026-03-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_analysis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='status',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
    ]
